export {default as MainPage} from './MainPage'
export {default as JoinPage} from './JoinPage'
export {default as LoginPage} from './LoginPage'
export {default as WritePage} from './WritePage'
export {default as UserPage} from './UserPage'
export {default as SettingPage} from './SettingPage'
